ALERT_ICON_STOP const "16"
ALERT_ICON_QUESTION const "32"
ALERT_ICON_EXCLAMATION const "48"
ALERT_ICON_INFORMATION const "64"

ALERT_BUTTON_OK const "0"
ALERT_BUTTON_YESNOCANCEL const "3"

ALERT_ID_OK const "1"
ALERT_ID_CANCEL const "2"
ALERT_ID_ABORT const "3"
ALERT_ID_RETRY const "4"
ALERT_ID_IGNORE const "5"
ALERT_ID_YES const "6"
ALERT_ID_NO const "7"
ALERT_ID_NONE const "0"

ALERT_RUNTIME_CONSOLE const "0"
ALERT_RUNTIME_GUI const "1"
ALERT_RUNTIME_BROWSER const "2"

ALERT_CRLF init 0x7f
ALERT_CONSOLE_CRLF init 0x0d,0x0a

alertboxShow external "plblib-adjacency-alertbox;alertbox"
