////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    
//
// plblib-adjacency-alertbox  
//
// © 2026 by Adjacency Global Solutions LLC 
//
// This work is licensed under Creative Commons Attribution-ShareAlike 4.0 International. To view a copy of this 
// license, visit https://creativecommons.org/licenses/by-sa/4.0/
//
//
// CC BY-SA 4.0
// Creative Commons Attribution-ShareAlike 4.0 International
//
// This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, 
// and build upon the material in any medium or format, even for commercial purposes. If others remix, adapt, or build 
// upon the material, they must license the modified material under identical terms.
//
// BY: Credit must be given to you, the creator.
// SA: Adaptations must be shared under the same terms
//
// In short, you are free to use this however you like. If you make changes, you have to include this license in your
//  modified works.
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
alertboxShow external "plblib-adjacency-alertbox;alertbox"      // defines exteral function for showing alert box
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
